Draft: Share AMIs publicly based on public_image flag [RHELDST-16452]
release-engineering/pubtools-ami pull request #93
Opened 2023-03-08 11:07 UTC by MichalHaluza

pushsource and cloud-image-tools recently implemented the support for a flag designating whether the image should be released publicly (i.e. shared to group "all") which is set in staged metadata instead of the hardcoded rule for hourly images in pubtools-ami. This commit implements the remaining part which controls the actual behavior responsible for sharing the images publicly during pub image pushes.

As backwards-compatible behavior, the hourly images without any public_image flag set in the metadata are still considered to be public and handled as such.

2023-03-08 23:24 UTC, rohanpm approved these changes

2023-03-08 23:26 UTC, rohanpm requested changes
Ah, as shown by CI the requirements files will need updating to require new pushsource, but code changes look fine.

2023-03-09 04:12 UTC, rajulkumar approved these changes

2023-03-09 18:49 UTC, rajulkumar approved these changes

2023-03-10 11:09 UTC, merged